CREATE TABLE if not exists urlservice
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    long_url  text,
    short_url VARCHAR(255),
    count     BIGINT                                  NOT NULL,
    CONSTRAINT pk_urlservice PRIMARY KEY (id)
);
