name: project build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql
          sudo service postgresql start
          # Optionally, you can configure PostgreSQL here
      - name: Build with Maven
        run: mvn clean install